[package]
name = "note"
version = "0.1.0"
authors = ["nielsing"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
colored = "1.9"
dirs = "2.0"
regex = "1"
